# Generated by Django 5.2.3 on 2025-06-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusBuilding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('building_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('building_name_he', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'DormitoriesPlus_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusInventorytracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('photo_url', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name_he', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'DormitoriesPlus_inventorytracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'DormitoriesPlus_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_he', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DormitoriesPlus_message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=20)),
                ('fault_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('fault_type', models.CharField(blank=True, max_length=50, null=True)),
                ('urgency', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_note_en', models.TextField(blank=True, null=True)),
                ('admin_note_he', models.TextField(blank=True, null=True)),
                ('fault_description_en', models.TextField(blank=True, null=True)),
                ('fault_description_he', models.TextField(blank=True, null=True)),
                ('fault_type_en', models.CharField(blank=True, max_length=50, null=True)),
                ('fault_type_he', models.CharField(blank=True, max_length=50, null=True)),
                ('note_en', models.TextField(blank=True, null=True)),
                ('note_he', models.TextField(blank=True, null=True)),
                ('urgency_en', models.CharField(blank=True, max_length=20, null=True)),
                ('urgency_he', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'DormitoriesPlus_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('notes_en', models.TextField(blank=True, null=True)),
                ('notes_he', models.TextField(blank=True, null=True)),
                ('room_number_en', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number_he', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'DormitoriesPlus_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusRoomassignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
            ],
            options={
                'db_table': 'DormitoriesPlus_roomassignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('role', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('field_encrypted_id_number', models.CharField(blank=True, db_column='_encrypted_id_number', max_length=255, null=True)),
                ('field_encrypted_phone', models.CharField(blank=True, db_column='_encrypted_phone', max_length=255, null=True)),
            ],
            options={
                'db_table': 'DormitoriesPlus_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DormitoriesPlus_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DormitoriesplusUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'DormitoriesPlus_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistBlacklistedtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blacklisted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'token_blacklist_blacklistedtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklistOutstandingtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('jti', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'token_blacklist_outstandingtoken',
                'managed': False,
            },
        ),
    ]
